name: Merge from upstream
on: 
  schedule:
    - cron: '0 0 * * *'
    # scheduled for 00:00 every day

jobs:
  merge-from-upstream-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: upstream
          fetch-depth: 0

      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          useremail: ${{ github.event.inputs.useremail }}
          username: ${{ github.event.inputs.usename }}
          upstream: nanoframework/nf-interpreter
          upstream-branch: develop
          branch: orgpal-mesh
